### ISSUE TITLE
srestore dclip

### ISSUE THREAD

**Issue by Z4ST1N** [HomeOfVapourSynthEvolution/havsfunc#10]
I think the Bicubic call at line 1634 is causing this error for a friend who tried using srestore with default settings

```
Error on frame 1425 request:
Resize error: Resize error 3074: no path between colorspaces (2/2/2 => 1/2/2). May need to specify additional colorspace parameters.
```

can't really confirm anything though since it wasnt me. as for why it even happened in the first place, he probably had it in 16 bit or something.

Also, at line 1592

```    if dclip is not None and not isinstance(dclip, vs.VideoNode):
        raise TypeError('srestore: dclip is not a clip')
    else:
        dclip = source
```
isn't this overwriting "dclip" when it's supplied? idk what its for (or what anything on this filter does tbh) but this seems like a goof

**Comment by HolyWu** [comment]
It would be nice if your friend can provide a screenshot of `text.ClipInfo` for the input clip of srestore.

Thanks for the second problem. The isinstance check should be placed in another if statement.

**Comment by theChaosCoder** [comment]
I had the same error today. I know it worked with 16bit before, something changed in srestore or in a recent vs version. 

```
clip = core.std.BlankClip(format=vs.YUV420P8) # ok
clip = core.std.BlankClip(format=vs.YUV420P16) # same resize error
clip = haf.srestore(clip, frate = 23.976)
```

**Comment by HolyWu** [comment]
Thanks for your report. Get fixed now.
