### ISSUE TITLE
MinBlur & Hqdn3d

### ISSUE THREAD

**Issue by Helenerineium** [HomeOfVapourSynthEvolution/havsfunc#14]
[line 4600](https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/master/havsfunc.py#L4600) may be of interest: preblur in LSFmod can be replaced by MinBlur(1) which is more optimized.

**Comment by Helenerineium** [comment]
Another issue: latest [hqdn3d](https://github.com/theChaosCoder/vapoursynth-hqdn3d) has the correct namespace (hqdn3d.Hqdn3d)

**Comment by HolyWu** [comment]
Thanks. Both are fixed now.
