### ISSUE TITLE
QTGMC

### ISSUE THREAD

**Issue by Helenerineium** [HomeOfVapourSynthEvolution/havsfunc#15]
https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/753846110a0917668c98a82a7d4560f4fe681661/havsfunc.py#L1101
I think this is a remnant from the old Avisynth and can be safely removed.

Also, mv.Mask only support 8-bit input at the moment, you may want to implement a workaround on this.

**Comment by Helenerineium** [comment]
Please have a look at #16
After that, you can close this issue.

**Comment by HolyWu** [comment]
Thank you. I'm quite busy at my job recently and will be inactive for a long time :(
