### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by WolframRhodium** [HomeOfVapourSynthEvolution/havsfunc#17]
Float values are passed to integer arguments at some places, which causes errors.

Examples:
1. all the values of `crop_args` at L2975
2. `thSADC`,  `thSADC2` at L2924, L2926, respectively

**Comment by HolyWu** [comment]
The funny thing is that the following script doesn't produce any error in vspipe or vsedit on my computer, at least in VS R44. I assume vapoursynth module silently convert float values to integer by truncation when the arguments are of integer type since one of the releases long time ago.

```python
from vapoursynth import core
clip = core.std.BlankClip()
clip = core.std.Crop(clip, left=1.2, right=3.4, top=5.6, bottom=7.8)
clip.set_output()
```

**Comment by WolframRhodium** [comment]
The script also works on my computer in VS R43.
I decide to close the issue now. It does indicates people should update their VS to the modern ones.
