### ISSUE TITLE
Srestore

### ISSUE THREAD

**Issue by nobananasforyou** [HomeOfVapourSynthEvolution/havsfunc#20]
Hello,

Could you please update Srestore? 

Script: https://pastebin.com/JYBjMBvx

I found an older version of the script in case you need it: https://svn.0x00ff00ff.com/mirror/package/avisynth/x86/plugins/Srestore.avsi

Thank you!

**Comment by HolyWu** [comment]
The changes made by AmjadSONY (a.k.a. real.finder) are mostly related to AVS+'s native high bit depth support and relevant MaskTools updates. Nothing really useful in VS side.
