### ISSUE TITLE
mcdaa3 and daa3mod

### ISSUE THREAD

**Issue by nobananasforyou** [HomeOfVapourSynthEvolution/havsfunc#22]
Would it be possible for you to add the following functions?
https://pastebin.com/kLdhdE6s <-- mcdaa3 and daa3mod.

However, there is a variant of daa3mod that I've not tested.
https://forum.doom9.org/showpost.php?p=1639679&postcount=89

Thank you.

**Comment by nobananasforyou** [comment]
Thank you!

**Comment by realfinder** [comment]
mcdaa3 was not really mc, it was the 1st function I made so I was noob back then, it should be madaa3 but anyway I already made new function called smam (see the edit2 in the doom9 link)
