### ISSUE TITLE
Deblock_QED Bug

### ISSUE THREAD

**Issue by AlphaAtlas** [HomeOfVapourSynthEvolution/havsfunc#23]
Running Deblock_QED on a clip with the default parameters give me some strange image corruption:

![bug0](https://user-images.githubusercontent.com/46462706/68541558-e1ee5400-036e-11ea-9101-56e2fc35b24d.png)

Seems to happen on everything from dinky 480p files, to YouTube downloads, to rips, and converting to different RGB/YUV formats doesn't seem to help. Here's the script that produces it:

```
import havsfunc as haf
import vapoursynth as vs
from vapoursynth import core

clip = core.ffms2.Source(r"""pathtovideo.mkv""")
clip = haf.Deblock_QED(clip)
clip.set_output()
```

That's the output from VSEdit's preview with VS R48, both in the VapourSynth Fatpack and a regular, non portable install. Interestingly, functions that depend on Deblock_QED (like AutoDeblock) outright crash VSEdit.

**Comment by HolyWu** [comment]
I cannot reproduce it. Tried on 480p, 720p, 1080p and all worked fine. Does it still happen if you add **core.std.SetMaxCPU("none")** right after importing core?

**Comment by AlphaAtlas** [comment]
Oddly enough that fixes it. I get corruption without that line, no corruption with it.

**Comment by HolyWu** [comment]
Then there probably is something wrong with your installation? I tried **core.std.SetMaxCPU("sse2")** and **core.std.SetMaxCPU("avx2")** with the latest R48 release and both instruction sets work just fine.

**Comment by AlphaAtlas** [comment]
Yeah, that's what I was afraid of. I'll have access to an avx2 CPU again relatively soon, and I guess I could try VS in Linux tomorrow.

**Comment by AlphaAtlas** [comment]
Closing this, as its not unique ti Deblock_QED and I believe its a VS SIMD issue on my old CPU...
