### ISSUE TITLE
Add support for interlaced video (or warn if it's not supported)

### ISSUE THREAD

**Issue by tvasenin** [HomeOfVapourSynthEvolution/havsfunc#24]
ATM, it's not clear for some filters, if they support interlaced input or not.

E.g., current MCTD port doesn't seem to support it (unlike Avisynth version), but the status is not mentioned anywhere.
Another example is Deblock_QED and probably many other filters.

VS has support for hinting field type and order via **_FieldBased**/**_Field** properties.

The proposal is to honor these props when present and use them to either support interlaced input or (at least) throw error if it is not supported.

**Comment by HolyWu** [comment]
Won't fix. Too much effort and too less benefit. Most users would apply filters/functions after IVTC/Deinterlacing if the source is telecined/interlaced.
