### ISSUE TITLE
QTGMC: SrchClipPP=3 results in corrupt clips

### ISSUE THREAD

**Issue by chriskretler** [HomeOfVapourSynthEvolution/havsfunc#26]
Using havsfunc r32, vapoursynth r48 on ubuntu 18.04

SrchClipPP=3 is resulting in a corrupt clip. See the round face-off circle and misplaced yellow portion by the player benches
![image](https://user-images.githubusercontent.com/16085459/75097423-a91e6780-5578-11ea-9df9-60eb9f6376ef.png)

The left frame is:QTGMC(orig, Preset='slower',TFF=True)
The right frame is: QTGMC(orig, Preset='slower',TFF=True,SrchClipPP=2)

To debug, I have created a separate script which recreates QTGMC a piece at a time. It appears the problem is created here:

`    else:
        expr = 'x {i} + y < x {i} + x {i} - y > x {i} - y ? ?'.format(i=scale(3, peak))
        tweaked = core.std.Expr([repair0, bobbed], expr=[expr] if ChromaMotion or isGray else [expr, ''])
        expr = 'x {i} + y < x {j} + x {i} - y > x {j} - x 51 * y 49 * + 100 / ? ?'.format(i=scale(7, peak), j=scale(2, peak))
        srchClip = core.std.Expr([spatialBlur, tweaked], expr=[expr] if ChromaMotion or isGray else [expr, ''])`

The resulting srchClip looks like a mask, which corrupts the resulting motion search function. This is what srchClip looks like:
![image](https://user-images.githubusercontent.com/16085459/75097502-73c64980-5579-11ea-8881-dd75e403d0fc.png)

Let me know what other information I can provide to assist.

**Comment by HolyWu** [comment]
Please cut an unprocessed sample for investigation. Thanks.

**Comment by chriskretler** [comment]
Further testing indicates that the issue was introduced in Vapoursynth R48, which modified the 'expr' function. I can fix this by rolling back to R47.2. Frankly, I don't know enough to determine whether this is:

- a bug in vapoursynth introduced in R48
- a change in behavior in the expr function that havsfunc needs to accommodate
- something else.

Here's a link to a small sample vob:
https://www.dropbox.com/s/z21uuqjaj1wxh84/sample.vob?dl=0

and companion script file:
https://www.dropbox.com/s/zcf4jvl7yom4a1e/sample.vpy?dl=0

**Comment by HolyWu** [comment]
I'm using VS r48, but I can't notice any significant artifacts between SrchClipPP=2 and SrchClipPP=3 from the sample vob. Does it make a difference if you insert **core.std.SetMaxCPU("none")** below vs.get_core()?

**Comment by chriskretler** [comment]
Ahh, yes it does make a difference. All of the corruption disappears when using R48 and everything appears as it should.

What does that mean to you? I have to admit I don't know how the including that option changes the execution process.

**Comment by HolyWu** [comment]
[SetMaxCPU](https://github.com/vapoursynth/vapoursynth/blob/master/doc/functions/setmaxcpu.rst). For unknown reason it's not listed on http://www.vapoursynth.com/doc/functions.html.

The strange thing is that the known expr bugs between R47 and R48-RC should already been fixed in the latest R48 and I don't see any corruption no matter I use SetMaxCPU("avx2") or SetMaxCPU("sse2") on your sample.

**Comment by chriskretler** [comment]
Thank you HolyWu!
