### ISSUE TITLE
FineDehalo produces white outlines 

### ISSUE THREAD

**Issue by theChaosCoder** [HomeOfVapourSynthEvolution/havsfunc#27]
```
clip = random source with edges
clip = mvf.Depth(clip, 10)
clip = haf.FineDehalo(clip)
```
8 and 16 bit depth are ok.

EDIT
DeHalo_alpha is also affected

EDIT2

I think the problem starts here `so = core.std.Expr([ugly, are], expr=[expr])`
https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/7d4a57e93e11d85fbba6f8f92845f00676ff9300/havsfunc.py#L415
Looks more like an Expr bug.

I'm using R49, x64 win10, Ryzen 2600

**Comment by HolyWu** [comment]
Um...DeHalo_alpha is fixed, but FineDehalo still persists.

**Comment by theChaosCoder** [comment]
I noticed that dehalo_alpha looked ok with `core.std.SetMaxCPU("none")` before your fix.
Yes FineDehalo still looks weird.

I think this is the first line with different output

**Comment by nobananasforyou** [comment]
Does this mean HQDeringmod and EdgeCleaner are also affected by this?

**Comment by theChaosCoder** [comment]
Looks good now, thx.

**Comment by HolyWu** [comment]
> Does this mean HQDeringmod and EdgeCleaner are also affected by this?

If you don't see obvious artifacts when preview your script, then probably not.
