### ISSUE TITLE
Deblock_QED doesn't work with Deblock r6

### ISSUE THREAD

**Issue by eXmendiC** [HomeOfVapourSynthEvolution/havsfunc#3]
I updated my stuff today and got this:
https://cdn.discordapp.com/attachments/224104675031384065/325597344051757056/unknown.png

With Deblock r5 everything works fine.  So, I guess the function needs an update for the newest version?

**Comment by HolyWu** [comment]
No, the function in this script doesn't need any change. The error message you get means that the deblock plugin isn't successfully loaded by VS core, which I have no idea why. Please use [Dependency Walker](http://www.dependencywalker.com/) to open the r6 dll file. Go to `File`->`Save`, change the type from `*.dwi` to `*.txt` (no need Import/Export Lists). Then upload the saved txt file somewhere.

**Comment by eXmendiC** [comment]
https://pastebin.com/buCAJxFe

**Comment by HolyWu** [comment]
Looks okay to me. Strange.

Try this one and see whether it works.
http://www.mediafire.com/file/9472q5ohk3r2hhk/Win64.7z

**Comment by eXmendiC** [comment]
Nope, the same error.

**Comment by HolyWu** [comment]
Try this one again which is compiled by ICC instead of GCC.
https://www.mediafire.com/?zbqg7xvzotx1sh7

**Comment by eXmendiC** [comment]
That works. However, the normal r6 now as well?
I updated my Vapoursynth to r38 (and had r37 before that). 
Could that be the problem why the newest Deblock didn't work?

**Comment by HolyWu** [comment]
I guess it is. The API version has changed in R38 (from 3.4 to 3.5). Next time I know I should ask people to update VS to the latest version first :D
