### ISSUE TITLE
FineDehalo produces white outlines p2

### ISSUE THREAD

**Issue by nobananasforyou** [HomeOfVapourSynthEvolution/havsfunc#30]
Hello,

I've grabbed your latest commit and am running vs r50, and yet I am still seeing white outlines. I've done an image comparison.

src > avs > vs, in that order: https://slow.pics/c/ch3n9DXr

Alternatively, you can download the images from dropbox: https://www.dropbox.com/s/3vm9rkxpdplzky0/s5.rar?dl=0

Here's the vs script:
import vapoursynth as vs
import havsfunc as haf
import fvsfunc as fvf
core = vs.get_core()

src = core.d2v.Source(r'sad', rff=False)
src = core.std.ShufflePlanes(src, planes=0, colorfamily=vs.GRAY)
src = fvf.Depth(src, 16)
src = haf.FineDehalo(src, darkstr=0)
src = fvf.Depth(src, 10)
src.set_output()

avs script:
MPEG2Source("sad.d2v", cpu=0)
finedehalo(darkstr=0)

**Comment by theChaosCoder** [comment]
If you show the mask, this is what it looks like  https://i.imgur.com/MFUG6Bu.png
For 8-12bit the mask looks the same.

**Comment by nobananasforyou** [comment]
Thanks for the follow up. I thought I was just imaging this.

**Comment by theChaosCoder** [comment]
I compared the output line for line and the biggest difference starts here. Look at the edges.
```
# This mask is almost binary, which will produce distinct discontinuities once applied. Then we have to smooth it
    shrink = shrink.std.Convolution(matrix=[1, 1, 1, 1, 1, 1, 1, 1, 1]).std.Convolution(matrix=[1, 1, 1, 1, 1, 1, 1, 1, 1])
    return shrink
```

![image](https://user-images.githubusercontent.com/3579830/82683805-e666c400-9c51-11ea-9f12-259641b49e0b.png)

**Comment by sekrit-twc** [comment]
![Untitled](https://user-images.githubusercontent.com/2678995/82706063-b73e5b80-9c2d-11ea-8a16-369736febfe2.png)

The input to std.Convolution already has those extra edges. Are you sure the problem begins there?

**Comment by theChaosCoder** [comment]
You are right. I skipped one line xD
It begins with the line above with `mt_inpand_multi(shrink, mode='ellipse', sw=rx_i, sh=ry_i)`

**Comment by sekrit-twc** [comment]
Isn't it because mt_inpand_multi maps to std.Minimum, but the original is something else?

```
	(mode_m != "") ? src.mt_expand (
\		thY=thY, thC=thC, mode=mode_m,
\		offx=offx, offy=offy, w=w, h=h, y=y, u=u, v=v, chroma=chroma
\	).mt_expand_multi (
\		thY=thY, thC=thC, mode=mode,
\		offx=offx, offy=offy, w=w, h=h, y=y, u=u, v=v, chroma=chroma,
\		sw=sw-1, sh=sh-1
\	) : src
```

**Comment by theChaosCoder** [comment]
I found this https://github.com/pinterf/masktools/issues/11

> Btw VS and AVS+ mt_expand/inpand_multi have identical output ans same speed.

**Comment by theChaosCoder** [comment]
Idk maybe the issue starts with the first edge mask. The avs version looks like something between sobel and prewitt. 
I think it looks a bit better if I replace `edges = src.std.Sobel() ` with `edges = src.std.Prewitt()`

**Comment by sekrit-twc** [comment]
Could be running into the issue where masktools Prewitt/Sobel/etc. are something else entirely:

http://avisynth.nl/index.php/MaskTools2/Mt_edge

                 "prewitt" is a more robust kernel and is equivalent to: 

                mt_logic(mt_logic(mt_edge("1 1 0 1 0 -1 0 -1 -1 1"),mt_edge("1 1 1 0 0 0 -1 -1 -1 1"),mode="max"),mt_logic(mt_edge("1 0 -1 1 0 -1 1 0 -1 1"),mt_edge("0 -1 -1 1 0 -1 1 1 0 1"),mode="max"),mode="max")

**Comment by HolyWu** [comment]
I will be busy for a while so I don't have much time to hunt down the culprit now. But neither "sobel" nor "prewitt" in AviSynth mt_edge's definition adheres to the standard operators, as already have been mentioned at https://forum.doom9.org/showthread.php?p=1839201#post1839201.

**Comment by theChaosCoder** [comment]
But as a first fix Sobel could be replaced with Prewitt as it seems to be closer to avisynths "prewitt".
![image](https://user-images.githubusercontent.com/3579830/82723091-91b45f00-9ccc-11ea-9ef8-ac9b353c48df.png)

Here's the same shrink output from above. I only replaced Sobel with Prewitt.
![image](https://user-images.githubusercontent.com/3579830/82723187-43ec2680-9ccd-11ea-9ba8-14f1f934b680.png)

**Comment by theChaosCoder** [comment]
@HolyWu You actually ported the avs prewitt already: http://forum.doom9.net/showthread.php?p=1839201#post1839201
But the difference is not that big between std.Prewitt and "avs Prewitt".
```
# mt_edge("prewitt", 0, 255)
clip1 = core.std.Expr([core.std.Convolution(clip, matrix=[1, 1, 0, 1, 0, -1, 0, -1, -1], saturate=False), core.std.Convolution(clip, matrix=[1, 1, 1, 0, 0, 0, -1, -1, -1], saturate=False)], 'x y max')
clip2 = core.std.Expr([core.std.Convolution(clip, matrix=[1, 0, -1, 1, 0, -1, 1, 0, -1], saturate=False), core.std.Convolution(clip, matrix=[0, -1, -1, 1, 0, -1, 1, 1, 0], saturate=False)], 'x y max')
clip = core.std.Expr([clip1, clip2], 'x y max')
```

**Comment by HolyWu** [comment]
I replaced Sobel with AvsPrewitt. See if it's better now.

**Comment by nobananasforyou** [comment]
It's a little bit better but it still results in halos around the eyes and nose.
![](https://i.imgur.com/S3BCtBC.png)

**Comment by theChaosCoder** [comment]
I noticed that Dehalo_alpha blurs the img more then the avs version 
All I did was to return the halos var
https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/39c2e9dc6604658600210c88717c6c56f5efa3d2/havsfunc.py#L413
I checked both m4() results, they match with avs 
So why does it blur more?
![image](https://user-images.githubusercontent.com/3579830/82749359-052b9e80-9da9-11ea-8bb7-29b92b683d0e.png)

**Comment by HolyWu** [comment]
Ah...the Bicubic default in zimg has changed to Catmull-Rom instead of Mitchell-Netravali, causing the result not as blurry as before. Try the latest commit again.

**Comment by theChaosCoder** [comment]
I would say it is very close to avs finedehalo now.
![image](https://user-images.githubusercontent.com/3579830/82750289-67879d80-9daf-11ea-8450-4d1be525ca44.png)

**Comment by theChaosCoder** [comment]
But I wonder which avs ports are also affected by this bicubic change...

**Comment by theChaosCoder** [comment]
Would this line also be affected in FineDehalo2() ? https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/master/havsfunc.py#L676

I think there are only 2 potential other candidates
bbmod https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/master/havsfunc.py#L3616
and
GrainFactory3 https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/master/havsfunc.py#L3749

**Comment by HolyWu** [comment]
It doesn't matter in FineDehalo2 since Bicubic is only used for converting gray mask to the input format when the user wants to show the mask.

bbmod and GrainFactory3 have explicitly specified `filter_param_a` and `filter_param_b` so they are fine as well.

**Comment by nobananasforyou** [comment]
@HolyWu your latest commit resolves this issue. Thank you so much. Cheers!
