### ISSUE TITLE
santiag

### ISSUE THREAD

**Issue by nobananasforyou** [HomeOfVapourSynthEvolution/havsfunc#31]
Currently, the default value of strv and strh is set to 1 and for a few sources they are really strong. Is there a possibility to add float support to santiag? Essentially, I just want the ability to assign values lower 1 because right now it's just 1 through 4 and there's no in between. 

Kind Regards.

Thank you.

**Comment by HolyWu** [comment]
No, because `strh` and `strv` are simply meant for how many times to iterate. It's not something like `h` in KNLMeansCL or `sigma` in FFT3DFilter. However, the lowest value for `strh` and `strv` is 0, not 1.

**Comment by nobananasforyou** [comment]
ok
