### ISSUE TITLE
TIVTC port

### ISSUE THREAD

**Issue by ghost** [HomeOfVapourSynthEvolution/havsfunc#34]
Hello. I don't know where to write and how to contact you. I would like to ask you to port the TIVTC plugin https://github.com/pinterf/TIVTC for VapourSynth or Linux version of AviSynth.
The point is that all decimators work pretty badly, except TDecimate mode=2. More details in this discussion http://www.vapoursynth.com/discussion/#comment-18812 (there is an example of a problem video and syntax).
If you can compile TIVTC for Linux AviSynth or VapourSynth, that would be great.
https://github.com/pinterf/TIVTC/issues/14
I was told that TIVTC uses some WinAPI functions, but it is not necessary to port all (TDeint, mode 0,1,7). TDecimate mode=2 enough.

**Comment by artenaki** [comment]
TIVTC plugin ported for Linux AviSynth.
https://github.com/pinterf/TIVTC
https://github.com/pinterf/TIVTC/issues/14

**Comment by theChaosCoder** [comment]
There is a port now https://github.com/dubhater/vapoursynth-tivtc
