### ISSUE TITLE
SMDegrain ghosting

### ISSUE THREAD

**Issue by nobananasforyou** [HomeOfVapourSynthEvolution/havsfunc#37]
Hello,

Hope you are doing well! I've found a bug in SMDegrain and it's causing ghosting, It is present in both 8bit and 16bit. Here's an image comparison: https://slow.pics/c/ybHyzvou

Test Script:
src()
haf.SMDegrain(src, search=7)

Kind Regards

**Comment by HolyWu** [comment]
Have you compared the result with the AviSynth version? And please always provide a short sample video for easier investigation.

**Comment by nobananasforyou** [comment]
Here's a sample. Yes, this bug is present in both avs and vs.  Sorry for the delay.

https://www.dropbox.com/s/aym6ioujx4t0tok/a.d2v?dl=0
https://www.dropbox.com/s/7r2f89mhxmf7g4p/a.m2v?dl=0

**Comment by HolyWu** [comment]
A quick test shows that it's not related to `SMDegrain` at all. Invoking `mv.Degrain2` directly without using `SMDegrain` will also incur the same artifacts. The culprit in this case is `search=7`. Try other `search` values to see the difference.
