### ISSUE TITLE
[REQ] Please add Temporal Degrain v2.4.2

### ISSUE THREAD

**Issue by AIisCool** [HomeOfVapourSynthEvolution/havsfunc#49]
Hi HolyWu, would it be possible to add this [version of Temporal Degrain](https://drive.google.com/file/d/1S9hm01d4_ZxGVU62NZh4eSIndrRl1GJ_/view)?

Thanks.

**Comment by Selur** [comment]
@AIisCool: There's also a TemporalDegrain2 port in G41Fun.py (https://github.com/Selur/VapoursynthScriptsInHybrid/blob/master/G41Fun.py) but no clue on which verison ov TemporalDegrain2 it is based.

**Comment by nobananasforyou** [comment]
You can find it here: https://github.com/Irrational-Encoding-Wizardry/fvsfunc/blob/master/fvsfunc.py#L1140

**Comment by adworacz** [comment]
Just an FYI - I've updated the version pointed to by Selur. Its now based on version 2.6.3 of the AVS version of TemporalDegrain2. A few minor features are still missing, but the implementation is about 95% the same.

See: https://github.com/Selur/VapoursynthScriptsInHybrid/blob/cd0249c29e7bf63c230c25762d1b3fc89f817b95/G41Fun.py#L2194
