### ISSUE TITLE
FineDehalo Bug

### ISSUE THREAD

**Issue by nobananasforyou** [HomeOfVapourSynthEvolution/havsfunc#57]
Hi,

I tested FineDehalo on a source and found that calling it with these parameters haf.FineDehalo(src, darkstr=0, brightstr=2) resulted in line darkening inside and around the edges. I've made an image comparison for troubleshooting: https://slow.pics/c/XVl7ORfQ

Script:
import vapoursynth as vs
import havsfunc as haf
import lvsfunc as lvf
import mvsfunc as mvsf
import fvsfunc as fvf
core = vs.core

src = core.d2v.Source(r'is_01.d2v')
src = core.vivtc.VFM(src, order=1, cthresh=8, scthresh=8).vivtc.VDecimate()

src = fvf.Depth(src, 16)
src = haf.FineDehalo(src, darkstr=0, brightstr=2)
src = fvf.Depth(src, 10)

src.set_output()

**Comment by HolyWu** [comment]
Have you compared with the AviSynth version first?

**Comment by nobananasforyou** [comment]
Yes. The output is identical.

**Comment by HolyWu** [comment]
It probably means you shouldn't set `brightstr` to that high value then.

**Comment by nobananasforyou** [comment]
That is what is required for the source I am working on because FineDehalo(src, darkstr=0) does not cover all the bright halos.

**Comment by HolyWu** [comment]
The author of Dehalo_alpha mentioned that the range of darkstr/brightstr is 0.0 to 1.0. So values out of this range could produce unwanted result.
