### ISSUE TITLE
QTGMC version number and update history

### ISSUE THREAD

**Issue by Fifis** [HomeOfVapourSynthEvolution/havsfunc#64]
Dear all,

This is more of a book-keeping question. I have checked the QTGMC implementation on the AviSynth web site, and their version is 3.383. The file header says that the 2022 mod is due to A.SONY, based on v3.33d by Dogway. So this is a really hot plugin. The description in `havsfunc.py` says that the version is QTGMC 3.33. However, it seems that the GitHub has RefineMotion (added in commit `feecd8d3b2209d0b968e0808fc469ffff216e6e8`) just like the AVS+ QTGMC in the `realfinder` repository had on 2021-06-11 in commit `d153c3d01731573764229438551130305d8c1d92`.

Since I am lost, as a newbie, in tracking the changes between the AVS-stuff QTGMC and havsfunc QTGMC, it is possible to add a similar (very brief) change history somewhere in the comment? It would be really helpful to know what the last common ancestor of the AVS+ and VS versions was, which post-3.33 features from the AVS+ QTGMC were ported and which new HAVS-specific changes were made that are not found in the AVS-stuff QTGMC.

Thank you in advance!

**Comment by HolyWu** [comment]
Sorry, not interested. Git commit message is already kind of an update history.
