### ISSUE TITLE
QTGMC crashes with >8bit input

### ISSUE THREAD

**Issue by iamtherobin** [HomeOfVapourSynthEvolution/havsfunc#67]
Windows 7, Python 3.8.13, Vapoursynth R58, havsfunc 1376c9e

When passing a clip with greater than 8bit to QTGMC, vapoursynth exits with no errors raised.

QTGMC performs no check for bitdepth. If it does not support high bitdepth, it should raise an error. If it does, what is causing the crash?

**Comment by HolyWu** [comment]
It's caused by a bug in `std.Convolution` for SSE2 code path. AVX2 and C code paths are fine. See https://github.com/vapoursynth/vapoursynth/issues/870.
