### ISSUE TITLE
QTGMC output is broken

### ISSUE THREAD

**Issue by theChaosCoder** [HomeOfVapourSynthEvolution/havsfunc#7]
QTGMC output is broken since commit 11b4453b88b7525a99d18f11db7d3372b3dc76a9

Tested with haf.QTGMC(clip, TFF=True)

**Comment by HolyWu** [comment]
Can't reproduce. I don't have interlaced video at hand, hence I manually create one.

```python
import vapoursynth as vs
import havsfunc as haf
core = vs.get_core()

clip = core.lsmas.LibavSMASHSource('test1_480p.mp4')
clip = haf.Weave(core.std.SeparateFields(clip, True).std.SelectEvery(4, [0, 3]), True)
clip = core.std.StackHorizontal([clip, haf.QTGMC(clip, TFF=True)])

clip.set_output()
```

![Image](https://i.imgur.com/jLFyJL4.png)

So how dose the broken look like actually? What's the properties of your video?

**Comment by theChaosCoder** [comment]
It looks like this:
![image](https://user-images.githubusercontent.com/3579830/34383822-66816426-eb18-11e7-8566-119341f5f491.png)

A previous version (commit) looks fine. Maybe it has do do with nnedicl? (I have a RX480 8gb)
A simple NNEDI3CL() looks ok...
I'm also using VS R41-test2 https://forum.doom9.org/showthread.php?p=1827692#post1827692

**Comment by theChaosCoder** [comment]
ok funny thing, haf.QTGMC(clip, TFF=True,  **opencl=True**) looks ok!

**Comment by HolyWu** [comment]
Now you really confuse me. `opencl=False` is the default so `haf.QTGMC(clip, TFF=True)` has nothing to do with nnedi3cl, but znedi3. I have tested `opencl=False` and `opencl=True` and both look fine here.

**Comment by theChaosCoder** [comment]
I just found the problem: I had an older znedi version in my plugins folder!
