### ISSUE TITLE
Consider making nrmode=0 the default for HQDeringmod

### ISSUE THREAD

**Issue by shssoichiro** [HomeOfVapourSynthEvolution/havsfunc#71]
The current default nrmode results in a significant amount of blurring of details and textures. Using nrmode=0 alleviates this issue. Given that the filter, presumably, is targeting "HQ", I feel that the defaults should favor higher quality by using nrmode=0.

**Comment by HolyWu** [comment]
No more HQDeringmod here.

**Comment by shssoichiro** [comment]
What is supposed to be the equivalent of HQDeringMod in IEW? is it smooth_dering?

**Comment by HolyWu** [comment]
Yes.
