### ISSUE TITLE
MinBlur optimization

### ISSUE THREAD

**Issue by Z4ST1N** [HomeOfVapourSynthEvolution/havsfunc#8]
I managed to double the speed of MinBlur by axing the many MakeDiffs in favor of one Expr. Here's the [difference](https://www.diffchecker.com/oztmpANw) and a [test script](https://pastebin.com/raw/W0keGEuA) to make sure the output is the same. 

Also, line 4733 may be of interest: `mvf.LimitFilter(s16, core.fmtc.bitdepth(RG4, bits=16, planes=planes), thr=1, elast=2, planes=planes)`

since the thr parameter of LimitFilter is scaled to 8-bit, setting it to `1/16` instead of `1` for limiting mixed 12-bit & 16-bit processing would be better

**Comment by HolyWu** [comment]
Thanks for the suggestion. Applied in https://github.com/HomeOfVapourSynthEvolution/havsfunc/commit/47740691c59e9d4caa1956fde15abd016d551e67.
