### ISSUE TITLE
No motion mask in MCTemporalDenoise

### ISSUE THREAD

**Issue by adworacz** [HomeOfVapourSynthEvolution/havsfunc#81]
https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/7f0a9a7a37b60a05b9f408024d203e511e544a61/havsfunc.py#L3973-L3976

Any particular reason to not implement the motion masking feature of MCTemporalDenoise?

If there's no concrete reason, I'm happy to jump in and implement it. Doesn't look too complicated based on the AVS version.

**Comment by HolyWu** [comment]
https://github.com/dubhater/vapoursynth-mvtools/blob/6d805e232397cb08074dbb58cc02849f63b96714/src/MVMask.c#L329

https://github.com/dubhater/vapoursynth-mvtools/issues/16

**Comment by adworacz** [comment]
Ahhhh got it, thank you. 

Looks like another thing to add to my todo list. 

I’ll resolve this for now. We can address it when Mvmask supports higher bit depths. If the code isn’t too crazy, I might be able to add it myself.
