### ISSUE TITLE
missing (optional?)dependencies

### ISSUE THREAD

**Issue by sl1pkn07** [HomeOfVapourSynthEvolution/havsfunc#84]
Hi, 

seems have missing (optional?)dependencies:

awarpsharp2:
https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/13f8f2c51476fd12e02997bc49304db8e7bdf53d/havsfunc/havsfunc.py#L3759

f3kdb:
https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/13f8f2c51476fd12e02997bc49304db8e7bdf53d/havsfunc/havsfunc.py#L3616
https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/13f8f2c51476fd12e02997bc49304db8e7bdf53d/havsfunc/havsfunc.py#L3625

can it include in the readme?

greetings

**Comment by HolyWu** [comment]
Updated. Thanks.
